version: '2.2'
services:
  graylog-mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog-main:
    image: graylog/graylog:3.1
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
  #    - /graylog/config:/usr/share/graylog/data/config   # Don't need this, can just use some basic environment variables to set configuration as below. Keeping here for now until I'm happy with it
  #    - /graylog/plugin/ASDASD:/usr/share/graylog/plugin/ASDASD # link to single plugins - might be needed for the content pack later
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
    links:
      - graylog-mongo:mongo
      - graylog-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12900:12900"
      - "12201:12201"
      - "12201:12201/udp"
      - "5140:5140"
      - "5140:5140/udp"
