version: '2.4'
services:
  graylog-mongo:
    container_name: sophos_graylog_mongo
    hostname: sophos_graylog_mongo
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  graylog-elasticsearch:
    container_name: sophos_graylog_es
    hostname: sophos_graylog_es
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog-main:
    container_name: sophos_graylog_main
    hostname: sophos_graylog_main
    image: graylog/graylog:3.1
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
  #    - /graylog/config:/usr/share/graylog/data/config   # Don't need this, can just use some basic environment variables to set configuration as below. Keeping here for now until I'm happy with it
  #    - /graylog/plugin/ASDASD:/usr/share/graylog/plugin/ASDASD # link to single plugins - might be needed for the content pack later
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
    links:
      - graylog-mongo:mongo
      - graylog-elasticsearch:elasticsearch
    ports:
#      - "9000:9000"
      - "12900:12900"
      - "12201:12201"
      - "12201:12201/udp"
      - "5140:5140"
      - "5140:5140/udp"
  graylog-proxy:
    container_name: sophos_graylog_proxy
    hostname: sophos_graylog_proxy
    image: nginx
    links:
      - graylog-main
    ports:
      - 80:80
      - 443:443
    volumes:
      - /graylog/nginx/etc:/etc/nginx
      - /graylog/nginx/private:/etc/ssl/private